const actionType = {
  GET_TODOS_SUCCESS: "GET_TODOS_SUCCESS",
  GET_TODOS_FAILURE: "GET_TODOS_FAILURE",
  ADD_TODOS_SUCCESS: "ADD_TODOS_SUCCESS",
  ADD_TODOS_FAILURE: "ADD_TODOS_FAILURE",
  DELETE_TODOS_SUCCESS: "DELETE_TODOS_SUCCESS",
  DELETE_TODOS_FAILURE: "DELETE_TODOS_FAILURE",
  UPDATE_TODOS_FAILURE: "UPDATE_TODOS_FAILURE",
  UPDATE_TODOS_SUCCESS: "UPDATE_TODOS_SUCCESS",
  FILTER_TODOS_SUCCESS: "FILTER_TODOS_SUCCESS",
  FILTER_TODOS_FAILURE: "FILTER_TODOS_FAILURE",
};
export default actionType;
